---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: docs/README.md
  label: Homepage
  templates:
  - settings
upload_dir: docs/.vuepress
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: npm run docs:build
  publish_command: npm run docs:build
  output_directory: docs/.vuepress/dist
