---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: docs/README.md
  label: Homepage
  templates:
  - settings
upload_dir: docs/.vuepress/public
public_path: ''
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
